# Generated by Django 5.1.11 on 2025-07-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0010_remove_assettransfer_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
