# Generated by Django 5.1.11 on 2025-07-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0011_assettransfer_deleted_at_assettransfer_restored_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
