# Generated by Django 5.1.11 on 2025-07-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0014_rename_status_status_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
