# Generated by Django 5.1.11 on 2025-07-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0016_alter_asset_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='assettransfer',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='assettransfernotes',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='assettype',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='created',
            new_name='created_at',
        ),
    ]
