# Generated by Django 5.1.11 on 2025-08-16 16:19

import django.db.models.deletion
import trakset.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0018_alter_assettransfer_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_holder',
            field=models.ForeignKey(default=trakset.models.get_admin_for_default, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_holder', to=settings.AUTH_USER_MODEL),
        ),
    ]
