# Generated by Django 5.1.11 on 2025-08-18 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0019_alter_asset_current_holder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='send_admins_email_on_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='send_user_email_on_transfer',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_user_email_on_transfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
