# Generated by Django 5.1.11 on 2025-08-18 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0020_asset_send_admins_email_on_transfer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='send_user_email_on_transfer',
        ),
        migrations.AddField(
            model_name='asset',
            name='send_user_email_on_transfer',
            field=models.ManyToManyField(blank=True, related_name='send_user_email_on_transfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
