# Generated by Django 5.1.11 on 2025-08-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0021_remove_asset_send_user_email_on_transfer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='send_admins_email_on_transfer',
        ),
    ]
