# Generated by Django 5.1.11 on 2025-08-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0022_remove_asset_send_admins_email_on_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='security_tag_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
