# Generated by Django 5.1.11 on 2025-08-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0024_asset_deleted_at_asset_restored_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Asset (including deleted)',
                'verbose_name_plural': 'Assets (including deleted)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trakset.asset',),
        ),
        migrations.CreateModel(
            name='AssetTransferProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Asset Transfer (including deleted)',
                'verbose_name_plural': 'Asset Transfers (including deleted)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trakset.assettransfer',),
        ),
    ]
