# Generated by Django 5.1.11 on 2025-08-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0025_assetproxy_assettransferproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetproxy',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assettransferproxy',
            options={'verbose_name': 'Asset Transfer', 'verbose_name_plural': 'Asset Transfers'},
        ),
    ]
