# Generated by Django 5.1.11 on 2025-08-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0028_alter_asset_location_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='trakset.location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='trakset.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='trakset.assettype'),
        ),
    ]
