# Generated by Django 5.1.11 on 2025-08-25 10:44

import django.db.models.deletion
import trakset.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0030_alter_asset_location_alter_asset_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='trakset.assettype'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_holder',
            field=models.ForeignKey(default=trakset.models.get_admin_for_default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_holder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='trakset.location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='trakset.status', verbose_name='Status'),
        ),
    ]
