# Generated by Django 5.1.11 on 2025-08-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0031_remove_asset_type_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='type',
            new_name='status_type',
        ),
    ]
