# Generated by Django 5.1.11 on 2025-08-25 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0032_rename_type_status_status_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransfer',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='trakset.asset'),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
