# Generated by Django 5.1.11 on 2025-08-25 12:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0033_alter_assettransfer_asset_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='asset',
            managers=[
                ('global_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
