# Generated by Django 5.1.11 on 2025-08-25 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0036_alter_asset_asset_type_alter_asset_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransfer',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='trakset.asset'),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
