# Generated by Django 5.1.11 on 2025-08-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0037_alter_assettransfer_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trakset.assettype',),
        ),
        migrations.CreateModel(
            name='LocationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trakset.location',),
        ),
        migrations.CreateModel(
            name='StatusProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trakset.status',),
        ),
    ]
