# Generated by Django 5.1.11 on 2025-08-25 17:46

import django.db.models.deletion
import trakset.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0039_alter_assettransfer_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='trakset.assettype', verbose_name='Asset Type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_holder',
            field=models.ForeignKey(default=trakset.models.get_admin_for_default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_holders', to=settings.AUTH_USER_MODEL, verbose_name='Current Holder'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_locations', to='trakset.location', verbose_name='Asset Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='send_user_email_on_transfer',
            field=models.ManyToManyField(blank=True, related_name='send_user_email_on_transfer', to=settings.AUTH_USER_MODEL, verbose_name='Email on Transfer'),
        ),
    ]
