# Generated by Django 5.1.11 on 2025-08-25 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0040_alter_asset_asset_type_alter_asset_current_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='trakset.assettype'),
        ),
    ]
