# Generated by Django 5.1.11 on 2025-08-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0042_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfernotes',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettransfernotes',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettransfernotes',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
